import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/footer";
import ProductContextProvider from "@/contexts/product-context-provider";
import { getProducts } from "@/lib/server-utils";
import CartContextProvider from "@/contexts/cart-context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gaming Ocean TCG",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products = await getProducts();

  return (
    <html lang="en">
      <body
        className={`${inter.className} flex h-screen min-h-screen flex-col`}
      >
        <ProductContextProvider products={products}>
          <CartContextProvider products={products}>
            <SessionProvider>
              <Header />
              {children}
              <Footer />
            </SessionProvider>
          </CartContextProvider>
        </ProductContextProvider>
      </body>
    </html>
  );
}
